### ISSUE TITLE
v0.2.0 To-do list

### ISSUE THREAD

**Issue by kbarbary** [snfactory/cubefit#10]
### Investigations / Features

- [x] Why does galaxy model outside the MLA go smoothly to zero instead of being flat? *Answer: slow convergence to flat solution, early stopping. Increasing hyperparameters makes it flatter.*
- [x] Confirm that SN ringing is from FFT shifting: plot PSF realized & shifted vs just realized. *Answer: probably. There's an up-to-5% residual in one simple test I did.*
- [x] Find out whether MLA tilt is radians or degrees, ask Seb about the temperature. *Answer: all indications are that MLA tilt is in radians.  Temperature doesn't affect ADR much, but we should require it anyway*
- [x] Add x, y fit to header in cubefit-subtract output files. (CubeFit estimation of SN location in each epoch)
- [x] Improve plotting
    - [x] Indicate scale of residuals in timeseries plot
    - [x] Summing pixels over wavelength in timeseries plot smears out features via ADR. Can we do something better? *Show timeseries plot for multiple 1000A (or less) metaslices.*
    - [x] diagnostic plot for ADR - simple 3 panel plot showing ADR model used: dx vs wave, dy vs wave, dx vs dy with wavelength point labelled every 1000 A.
    - [x] Make new plots with data, model, residuals for each epoch.
    - [x] Change all file formats to png.

**Comment by kbarbary** [comment]
@cmsaunders I think in the timeseries plot, we should remove the option to show the intermediate steps, and instead show multiple "metaslices"/bands in the same plot. We can still plot intermediate steps, but we'd do that as entirely separate plots. We're now pretty sure the intermediate steps are working, so this is no longer as important.

Can you work on this or any of the other plotting changes?

**Comment by cmsaunders** [comment]
I'm already working on the plotting issues today, so I'll think about this.
I was thinking about changing the slice plot to meta-slices, but your idea
could just replace that plot. Do you want to see slices for the data,
model, and residuals? If so, it would be better to show that in the
per-epoch plots, since there will be so many subplots.

**Comment by kbarbary** [comment]
Yes, I was thinking to have three subplots per epoch per metaslice (data, model, residual). But yeah it would be a lot of panels. Maybe you can see how it looks?

We might just want to produce separate pngs for each epoch and have them all on the same html page. Dunno.

**Comment by kbarbary** [comment]
Pushed remaining issues to v0.3.0.

**Comment by kbarbary** [comment]
@nicolaschotard v0.2.0 should be ready to deploy.
