### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by kbarbary** [snfactory/cubefit#12]
- [x] Add option to not resample SN model
- [ ] Use CubeSim to create small test case that can be included with CubeFit and used in tests
- [ ] **[DOCS]** Document procedure more fully in README
- [ ] **[DOCS]** Tidy up docstrings

### Speculative

- [ ] Fit some of PSF parameters as in ExtractStar? [#3]
- [ ] Investigate remaining residuals (e.g., galaxy dipole residuals, galaxy-shaped residuals)
- [ ] Allow spatial gradient in sky?
- [ ] Use CubeSim to perform tests on hyperparameters

**Comment by kbarbary** [comment]
Closing this as all important items (that I actually plan on doing) have their own issues.
