### ISSUE TITLE
v0.1.0 To-do list

### ISSUE THREAD

**Issue by kbarbary** [snfactory/cubefit#5]
- [x] Instrument code with "logged results" - output of model & parameters after each fit stage.
- [x] Move all plotting to separate plotting script `ddt-plot` (or whatever name).
- [x] Investigate using PyFFTW with threads.
- [x] Make sure `FFTW(in, out, axes=(1, 2))` is equivalent to numpy's `fft2`
- [x] Run another iteration fitting galaxy using all exposures
- [x] Real logging.
- [x] remove sphinx stuff (no longer used); replace with latex docs from Seb.
- [x] Change output format to FITS
- [x] Explicitly document input config file schema & output FITS schema in README.
- [x] Fix bug in `fit_galaxy_sky_multi()` [#8]
- [x] Output FITS file for each epoch with galaxy (and sky?) subtracted
- [x] Add INFO output giving per-epoch chisq in galaxy fitting steps
- [x] In `fit_galaxy_sky_multi`, multiply regularization penalty by nepochs
- [x] Position fitting step: Convince ourselves that gradient function is correct and/or try different optimizer *Answer: It's not obviously wrong*
- [x] Run all test data
- [x] Remove hard-coded directory paths from `plotting.py`

**Comment by kbarbary** [comment]
@ycopin when we are writing subtracted cubes to be fed to ExtractStar, should the sky be subtracted, or just the galaxy?

**Comment by ycopin** [comment]
Just the galaxy, since ES will anyway take care of a uniform background. I'm confused on how you can subtract the sky, I guess you assume a perfect knowledge of the SN position and PSF.

**Comment by kbarbary** [comment]
OK, thanks. Changed it in e723dad.

Cubefit necessarily fits the sky in the process of fitting the galaxy to multiple epochs. The PSF model is fixed here, so yes, we are assuming perfect knowledge of the PSF. The SN position however, is allowed to vary.

**Comment by kbarbary** [comment]
A note on the optimizer in `fit_position_sky_sn_multi()`: I tried both `fmin` from scipy.optimize and `iminuit`, which are both gradient-free methods. Both of them ran for 30 minutes before I stopped them.

This optimization problem has ~30 parameters, so it's not easy for these minimizers. I think we do need a gradient-based method or to somehow better exploit the independence of most of the parameters (the Hessian is block diagonal except for covariance between SN position and all other parameters).

**Comment by ycopin** [comment]
Are all the parameters properly normalized? Otherwise, you could try to remove some of the parameters by fixing them to some not-too-bad values (e.g. sky level = median background).

**Comment by kbarbary** [comment]
@ycopin There are only position parameters in the fit, so normalization shouldn't be an issue. I've opened a new issue explaining the optimization problem in more detail: #9

**Comment by kbarbary** [comment]
Moved "future" bullet points to #10

**Comment by kbarbary** [comment]
@cmsaunders Can you clean up the `plot_sn` function in `plotting.py` a bit? It has a hard-coded directory path in it. (Make it take the path to the IDR as an input or just move the whole function out of the repo for now.)

**Comment by cmsaunders** [comment]
Will do.

**Comment by kbarbary** [comment]
Declared complete.
